# 巧用Github Action同步代码到Gitee https://yikun.github.io/2020/01/17/巧用Github-Action同步代码到Gitee/
name: Sync2Gitee_GiteeAutoPages

on:
  push:
    branches: # 在main分支有pr的时候触发
      - dev
      - dev-vuepress
      - main
      - gh-pages
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          # 支持Gitee, Github, Gitlab and Gitcode
          # GitHub 用户名
          src: github/dazer007
          # 支持Gitee, Github, Gitlab and Gitcode
          # Gitee 用户名
          dst: gitee/dazer007
          # 需要同步的仓库列表（逗号分隔）
          static_list: "dazer007.github.io"
          #参考-Gitee: 配置并保存ssh key和token：https://github.com/Yikun/hub-mirror-action?tab=readme-ov-file#faq
          # https://gitee.com/profile/sshkeys
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          #Giee Token: https://gitee.com/profile/personal_access_tokens
          dst_token: ${{ secrets.GITEE_TOKEN }}
          force_update: true #强制更新
          debug: true #输出debug信息
