name: push-2-ghpages
#GitHub Actions 实现提交代码自动打包部署到 gh-pages https://juejin.cn/post/7054872300922863624

on:
  pull_request: # 在main分支有pr的时候触发
    branches:
      - main
  push:
    branches: [main] # main 分支有 push 时触发;
    paths-ignore:   # 下列文件的变更不触发部署， 可以自行添加
      - README.md
  release:
    types: [published]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      # 下载源码
      # 这一步就是检出你的仓库并下载里面的代码到runner中,actions/checkout@v2是官方自己造的轮子，直接拿来用就行
      - name: Checkout
        uses: actions/checkout@v2

      # 打包构建
      - name: Build
        uses: actions/setup-node@master
        with:
          node-version: '16.x'
      - run: npm install # 安装依赖
      - run: npm run build # 打包

      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          publish_dir: ./docs/.vuepress/dist # 部署打包后的 dist 目录,常规项目都是： ./dist
          github_token: ${{ secrets.DEPLOY_SECRET }} # secret 名; 如果提示：push remote: Invalid username or password.，请更新的token
          user_name: ${{ secrets.MY_USER_NAME }}
          user_email: ${{ secrets.MY_USER_EMAIL }}
          commit_message: 来自Github Actions自动部署 "DEPLOY_DATE=$(date -d "${{ github.event.head_commit.timestamp }}" +"%Y-%m-%d %T")" # 部署时的 git 提交信息，自由填写
